displayName=Chat Color Manager
author=Cameron Jewell
support=
description=Recolor chat messages for better visibility and customization
tags=chat,color,utility
plugins=com.camjewell.ChatColorManagerPlugin
